### ISSUE TITLE
Question/Discussion: Exposing password for FritzBox

### ISSUE THREAD

**Issue by SHU-red** [sberk42/fritzbox_exporter#16]
Hi there,
im successfully using this in a docker container.

My question is:
Are there any issues with writing the password to my homerouter in clear text into my docker-compose script?
I didnt find a way to create a user on my fritzbox only for the node exporter and only with access to my data ... or did i miss something?

It feels weird to write the admin-password into some sort of script
... but maybe there is something im missing ...

**Comment by MaurizioB84** [comment]
in which way you create the container? can you share it?

**Comment by SHU-red** [comment]
Not sure what you are asking for.
This is the docker-compose i use from portainer as stack

```
version: '3'
services:
  node_exporter_fritzbox:
    image: kehrhardt/fritzbox_exporter:latest
    container_name: node_exporter_fritzbox
    ports:
      - "9042:9042"
    expose:
      - "9042"
    restart: unless-stopped
    environment:
      USERNAME: node_exporter
      PASSWORD: HEREIHAVETOEXPOSEMYPASSWORDFORMYCREATEDUSERNODE_EXPLORER
      GATEWAY_URL: http://fritz.box:49000
      LISTEN_ADDRESS: 0.0.0.0:9042
```

As soon as i deactivate the setting `FRITZ!Box Settings change for this user` i only get reduced information.
Maybe it is like it is, but it feels a bit strange to write down a "admin-password" this way
